#!/bin/bash
# Installs Elden Mod Manager on Steam Deck: downloads the latest Linux release
# (or uses a local build, for testing — see --zip/--dir below), installs it
# under ~/.local/share, creates a launch wrapper with the flags needed for the
# on-screen keyboard/overlay to work under gamescope, and (re)registers it as
# a non-Steam game for every local Steam user profile.
set -euo pipefail

REPO_OWNER="Mkeefeus"
REPO_NAME="Elden-Mod-Manager"
ASSET_PATTERN='^eldenmodmanager-.*-linux-portable-x64\.zip$'

APP_DISPLAY_NAME="Elden Mod Manager"
INSTALL_DIR="$HOME/.local/share/elden-mod-manager"
EXECUTABLE_PATH="$INSTALL_DIR/elden-mod-manager"
WRAPPER_PATH="$INSTALL_DIR/launch.sh"
LOG_DIR="$HOME/.config/elden-mod-manager/logs"
LOG_FILE="$LOG_DIR/steam-launch.log"

log() { echo "[install-steamdeck] $*"; }
die() {
  echo "[install-steamdeck] ERROR: $*" >&2
  exit 1
}
require_cmd() { command -v "$1" >/dev/null 2>&1 || die "Required command '$1' not found."; }

usage() {
  cat <<'USAGE'
Usage: install-steamdeck.sh [--zip PATH | --dir PATH]

  --zip PATH   Install from a local release zip instead of downloading the
               latest GitHub release (e.g. a build produced by `pnpm make`).
  --dir PATH   Install from a local, already-extracted build directory
               instead of downloading (e.g. `out/Elden Mod Manager-linux-x64`).
  -h, --help   Show this help.

With no arguments, downloads and installs the latest published GitHub release.
USAGE
}

LOCAL_ZIP=""
LOCAL_DIR=""
while [ $# -gt 0 ]; do
  case "$1" in
    --zip)
      [ $# -ge 2 ] || die "--zip requires a path argument"
      LOCAL_ZIP="$2"
      shift 2
      ;;
    --dir)
      [ $# -ge 2 ] || die "--dir requires a path argument"
      LOCAL_DIR="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      die "Unknown argument: $1"
      ;;
  esac
done

[ -z "$LOCAL_ZIP" ] || [ -z "$LOCAL_DIR" ] || die "--zip and --dir are mutually exclusive"

require_cmd python3
if [ -z "$LOCAL_ZIP" ] && [ -z "$LOCAL_DIR" ]; then
  require_cmd curl
fi

TMP_DIR=$(mktemp -d)
STEAM_WAS_RUNNING=0

cleanup() {
  rm -rf "$TMP_DIR"
  if [ "$STEAM_WAS_RUNNING" -eq 1 ] && command -v steam >/dev/null 2>&1; then
    log "Relaunching Steam..."
    nohup steam >/dev/null 2>&1 &
    disown
  fi
}
trap cleanup EXIT

# --- 1. Obtain the release: local dir, local zip, or latest from GitHub ----

COPY_INSTALL=0

if [ -n "$LOCAL_DIR" ]; then
  [ -d "$LOCAL_DIR" ] || die "Local directory not found: $LOCAL_DIR"
  log "Using local build directory: $LOCAL_DIR"
  EXTRACT_DIR="$LOCAL_DIR"
  COPY_INSTALL=1
else
  if [ -n "$LOCAL_ZIP" ]; then
    [ -f "$LOCAL_ZIP" ] || die "Local zip not found: $LOCAL_ZIP"
    log "Using local release zip: $LOCAL_ZIP"
    ZIP_PATH="$LOCAL_ZIP"
  else
    log "Querying latest release from GitHub..."
    RELEASE_JSON=$(curl -sL "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/latest")

    DOWNLOAD_URL=$(printf '%s' "$RELEASE_JSON" | python3 -c '
import json, re, sys
pattern = re.compile(sys.argv[1])
data = json.load(sys.stdin)
for asset in data.get("assets", []):
    if pattern.match(asset["name"]):
        print(asset["browser_download_url"])
        break
' "$ASSET_PATTERN")

    [ -n "$DOWNLOAD_URL" ] || die "Could not find a linux-portable-x64 release asset. Is the latest release published (not a draft)?"

    ZIP_PATH="$TMP_DIR/release.zip"
    log "Downloading $DOWNLOAD_URL"
    curl -sL -o "$ZIP_PATH" "$DOWNLOAD_URL" || die "Download failed"
  fi

  EXTRACT_DIR="$TMP_DIR/extracted"
  mkdir -p "$EXTRACT_DIR"
  python3 -c '
import sys, zipfile
with zipfile.ZipFile(sys.argv[1]) as z:
    z.extractall(sys.argv[2])
' "$ZIP_PATH" "$EXTRACT_DIR"
fi

# --- 2. Install ---------------------------------------------------------

# The release contents may or may not be wrapped in a single top-level folder
# depending on how they were packaged — handle either case.
ENTRIES=("$EXTRACT_DIR"/*)
if [ "${#ENTRIES[@]}" -eq 1 ] && [ -d "${ENTRIES[0]}" ]; then
  SOURCE_DIR="${ENTRIES[0]}"
else
  SOURCE_DIR="$EXTRACT_DIR"
fi

log "Installing to $INSTALL_DIR"
rm -rf "$INSTALL_DIR"
mkdir -p "$(dirname "$INSTALL_DIR")"
if [ "$COPY_INSTALL" -eq 1 ]; then
  # --dir points at a directory the caller likely wants to reuse (e.g. a
  # pnpm make output folder) — copy it rather than moving it away.
  cp -r "$SOURCE_DIR" "$INSTALL_DIR"
else
  mv "$SOURCE_DIR" "$INSTALL_DIR"
fi

[ -f "$EXECUTABLE_PATH" ] || die "Executable not found at $EXECUTABLE_PATH after extraction — unexpected release layout."
chmod +x "$EXECUTABLE_PATH"

# --- 3. Write the launch wrapper --------------------------------------------

mkdir -p "$LOG_DIR"
cat >"$WRAPPER_PATH" <<EOF
#!/bin/bash
# Generated by install-steamdeck.sh — re-run that script to regenerate.
mkdir -p "$LOG_DIR"
exec "$EXECUTABLE_PATH" --no-sandbox --disable-gpu-sandbox > "$LOG_FILE" 2>&1
EOF
chmod +x "$WRAPPER_PATH"
log "Wrapper written to $WRAPPER_PATH"

# --- 4. Register as a non-Steam game for every local user profile ----------

STEAM_ROOTS=()
for candidate in "$HOME/.local/share/Steam" "$HOME/.steam/steam" "$HOME/.steam/root"; do
  if [ -d "$candidate/userdata" ]; then
    STEAM_ROOTS+=("$(realpath "$candidate")")
  fi
done

if [ "${#STEAM_ROOTS[@]}" -eq 0 ]; then
  log "No Steam installation found — skipping non-Steam game registration."
  exit 0
fi

mapfile -t STEAM_ROOTS < <(printf '%s\n' "${STEAM_ROOTS[@]}" | sort -u)

USERDATA_DIRS=()
for root in "${STEAM_ROOTS[@]}"; do
  for d in "$root"/userdata/*/; do
    [ -d "$d" ] && USERDATA_DIRS+=("${d%/}")
  done
done

if [ "${#USERDATA_DIRS[@]}" -eq 0 ]; then
  log "No Steam user profiles found — skipping non-Steam game registration."
  exit 0
fi

if command -v steam >/dev/null 2>&1 && pgrep -x steam >/dev/null 2>&1; then
  STEAM_WAS_RUNNING=1
  log "Closing Steam..."
  steam -shutdown >/dev/null 2>&1 || true
  for _ in $(seq 1 30); do
    pgrep -x steam >/dev/null 2>&1 || break
    sleep 1
  done
  if pgrep -x steam >/dev/null 2>&1; then
    die "Steam did not shut down in time — aborting shortcut registration so it doesn't overwrite our changes. Close Steam manually and re-run this script."
  fi
fi

VDF_SCRIPT='
import struct, sys, binascii, os

TYPE_OBJECT = 0x00
TYPE_STRING = 0x01
TYPE_INT32 = 0x02
TYPE_END = 0x08

def read_cstring(data, pos):
    end = data.index(b"\x00", pos)
    return data[pos:end].decode("utf-8", errors="replace"), end + 1

def parse_object(data, pos):
    entries = []
    while True:
        type_byte = data[pos]
        pos += 1
        if type_byte == TYPE_END:
            return entries, pos
        key, pos = read_cstring(data, pos)
        if type_byte == TYPE_OBJECT:
            value, pos = parse_object(data, pos)
        elif type_byte == TYPE_STRING:
            value, pos = read_cstring(data, pos)
        elif type_byte == TYPE_INT32:
            value = struct.unpack("<i", data[pos:pos + 4])[0]
            pos += 4
        else:
            raise ValueError(f"Unknown VDF type byte {type_byte:#x} at offset {pos - 1}")
        entries.append([key, type_byte, value])

def serialize_object(entries):
    out = bytearray()
    for key, type_byte, value in entries:
        out.append(type_byte)
        out += key.encode("utf-8") + b"\x00"
        if type_byte == TYPE_OBJECT:
            out += serialize_object(value)
        elif type_byte == TYPE_STRING:
            out += value.encode("utf-8") + b"\x00"
        elif type_byte == TYPE_INT32:
            out += struct.pack("<i", value)
    out.append(TYPE_END)
    return bytes(out)

def serialize_file(root_key, entries):
    out = bytearray([TYPE_OBJECT])
    out += root_key.encode("utf-8") + b"\x00"
    out += serialize_object(entries)
    return bytes(out)

def generate_appid(exe, name):
    crc = binascii.crc32((exe + name).encode("utf-8")) & 0xffffffff
    top = crc | 0x80000000
    return top - 0x100000000 if top >= 0x80000000 else top

def find_entry_key(entries, app_name):
    for key, type_byte, value in entries:
        if type_byte != TYPE_OBJECT:
            continue
        for field_key, field_type, field_value in value:
            if field_key == "AppName" and field_type == TYPE_STRING and field_value == app_name:
                return key
    return None

def build_entry(app_name, exe_value, start_dir_value):
    return [
        ["appid", TYPE_INT32, generate_appid(exe_value, app_name)],
        ["AppName", TYPE_STRING, app_name],
        ["Exe", TYPE_STRING, exe_value],
        ["StartDir", TYPE_STRING, start_dir_value],
        ["icon", TYPE_STRING, ""],
        ["ShortcutPath", TYPE_STRING, ""],
        ["LaunchOptions", TYPE_STRING, ""],
        ["IsHidden", TYPE_INT32, 0],
        ["AllowDesktopConfig", TYPE_INT32, 1],
        ["AllowOverlay", TYPE_INT32, 1],
        ["OpenVR", TYPE_INT32, 0],
        ["Devkit", TYPE_INT32, 0],
        ["DevkitGameID", TYPE_STRING, ""],
        ["DevkitOverrideAppID", TYPE_INT32, 0],
        ["LastPlayTime", TYPE_INT32, 0],
        ["FlatpakAppID", TYPE_STRING, ""],
        ["tags", TYPE_OBJECT, []],
    ]

def main():
    vdf_path, app_name, exe_path, start_dir = sys.argv[1:5]
    exe_value = f"\"{exe_path}\""
    start_dir_value = f"\"{start_dir}\""

    if os.path.exists(vdf_path) and os.path.getsize(vdf_path) > 0:
        with open(vdf_path, "rb") as f:
            data = f.read()
        pos = 0
        if data[pos] != TYPE_OBJECT:
            raise ValueError("Unexpected root type in shortcuts.vdf")
        pos += 1
        root_key, pos = read_cstring(data, pos)
        entries, pos = parse_object(data, pos)
    else:
        root_key = "shortcuts"
        entries = []

    existing_key = find_entry_key(entries, app_name)
    new_entry = build_entry(app_name, exe_value, start_dir_value)

    if existing_key is not None:
        for i, (key, _type_byte, _value) in enumerate(entries):
            if key == existing_key:
                entries[i] = [key, TYPE_OBJECT, new_entry]
                break
    else:
        entries.append([str(len(entries)), TYPE_OBJECT, new_entry])

    with open(vdf_path, "wb") as f:
        f.write(serialize_file(root_key, entries))

main()
'

for userdata_dir in "${USERDATA_DIRS[@]}"; do
  config_dir="$userdata_dir/config"
  mkdir -p "$config_dir"
  vdf_path="$config_dir/shortcuts.vdf"

  backup_path=""
  if [ -f "$vdf_path" ]; then
    backup_path="$vdf_path.bak.$(date +%Y%m%d%H%M%S)"
    cp "$vdf_path" "$backup_path"
    log "Backed up $vdf_path to $backup_path"
  fi

  log "Registering non-Steam game in $vdf_path"
  if ! python3 -c "$VDF_SCRIPT" "$vdf_path" "$APP_DISPLAY_NAME" "$WRAPPER_PATH" "$INSTALL_DIR/"; then
    log "Failed to update $vdf_path"
    if [ -n "$backup_path" ]; then
      cp "$backup_path" "$vdf_path"
      log "Restored original file from backup"
    fi
    die "Aborting Steam shortcut registration due to an error updating $vdf_path"
  fi
done

log "Done. Elden Mod Manager should appear as a non-Steam game after Steam restarts."
